#version 450

layout (local_size_x = 8, local_size_y = 8) in;
layout (set = 0, binding = 0, rgba16f) uniform readonly image2D inImage;
layout (set = 1, binding = 0, rgba8) uniform writeonly image2D outImage;

vec3 LinearToSRGB(vec3 color)
{
    return pow(abs(color), vec3(1.0f/2.2f));
}

void main()
{
	ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
	vec4 inPixel = imageLoad(inImage, coord);

	vec3 outColor = LinearToSRGB(inPixel.rgb);
	imageStore(outImage, coord, vec4(outColor, 1.0));
}
